---
title: "Figure 1"
output: html_document
date: "2026-05-30"
editor_options: 
  chunk_output_type: console
---

PURPOSE: Create Figure 1


```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(collapse)
library(sf)
library(tigris)
library(openxlsx)
library(ggh4x)
library(patchwork)
library(ggrepel)
library(scales)
library(svglite)
library(RColorBrewer)
library(ggview)

options(scipen = 99999)

knitr::opts_chunk$set(echo = TRUE)
```


# Read in files 
```{r}
folder = "ADD PATH HERE"

## Farmworkers 
file <- paste0(folder, "/01a_final data/01_farmworker_imputation_pred.csv")
df.farmworker <- fread(file) %>%
  mutate(variable = case_when(
    variable %in% c("Hired Labor", "Unpaid Labor") ~ "Hired+Unpaid Labor",
    variable == "Migrant Labor (incl hired)" ~ "Migrant Labor"
  )) %>%
  group_by(Year, STATEFIPS, STATEABB, STATENAME, CNTYFIPS, GEOID, region_2, region_1, variable) %>%
  summarise(across(c(n_farmworkers, n_farmworker_imput), ~sum(.))) %>%
  filter(Year %in% 2008:2023) 


## Days of co-exposure to HI above thresholds
file = paste0(folder, "/01a_final data/03_HI_smoke_2008-2023.csv")
df.HI.smoke <- fread(file ) %>%
  mutate(region_2 = factor(region_2, levels = c(  "East North Central" , "Middle Atlantic",   "New England" ,
                                                 "West South Central", "East South Central" , "South Atlantic",
                                                 "Pacific", "Mountain", "West North Central" ))) %>%
  mutate(month.abb = fct_reorder(month.abb, month))

```



# Fig 1A - Bar graph of change in average annual coexpos days above threshold between 2019-2023 vs 2008-2012
## 80F and 90F
```{r}
## Count annual co-exposure days above threshold
df.HI.nDays.annual <- df.HI.smoke %>%
  mutate(coexpos = if_else(smokePM_pred.wtd > 0 , "coexpos_days", "no coexpos"),
         coexpos = if_else(is.na(smokePM_pred.wtd), "no coexpos", coexpos)) %>%
  fmutate(indicator = case_when(
    Year %in% 2008:2012 ~ "2008-2012",
    Year %in% 2019:2023 ~ "2019-2023"
  )) %>% 
  select(region_2, region_1, GEOID, STATEFIPS, STATEABB, CNTYFIPS, CNTYNAME, Year, month, month.abb, yearmonday, crop_class, total_county_crop_area, mean.HI.wtd, smokePM_pred.wtd, coexpos, indicator) %>%
  fgroup_by(GEOID, region_2, region_1, STATEFIPS, STATEABB, CNTYFIPS, CNTYNAME,crop_class, coexpos, Year, indicator) %>%
  fsummarise(n_days_80F = fsum(mean.HI.wtd >=80   &  coexpos == "coexpos_days"),
             n_days_90F = fsum(mean.HI.wtd >=90   &  coexpos == "coexpos_days"),
             n_days_100F = fsum(mean.HI.wtd >=100 & coexpos == "coexpos_days"),
             n_days_110F = fsum(mean.HI.wtd >=110 & coexpos == "coexpos_days")
             ) 

## Calculate difference in average annual co-exposure days between 2019-2023 vs 2008-2012 periods
df.n.county.reg.1 <- df.HI.nDays.annual %>%
  pivot_longer(names_to = "thresholds",
               values_to = "n Days >= threshold HI",
               cols = 12:15) %>%
  mutate(`thresholds` = factor(`thresholds`, 
                                           levels = c("n_days_80F",
                                                      "n_days_90F",
                                                      "n_days_100F",
                                                      "n_days_110F"))) %>%
  filter(coexpos == "coexpos_days",
         crop_class == 1) %>%
  ### average annual co-exposure days
  group_by(GEOID, region_2, coexpos, crop_class, indicator, thresholds) %>%
  summarise(n.avg.days = mean(`n Days >= threshold HI`)) %>%
  filter(thresholds %in% c("n_days_80F", "n_days_90F")) %>%
  select(indicator, region_2, GEOID, thresholds, n.avg.days) %>%
  ### Difference between 2019-2023 vs 2008-2012 in each county
  pivot_wider(names_from = indicator,
              values_from = n.avg.days) %>%
  mutate(diff.avg.days = `2019-2023` - `2008-2012` ) %>%
  ungroup() %>%
  select(-`NA`) %>%
  ### Average county change in coexposure days by region
  group_by( region_2, coexpos, crop_class, thresholds) %>%
  summarise(diff.avg.days = mean(diff.avg.days, na.rm = TRUE)) 

## assign thresholds colours
my_colours = colorRampPalette(brewer.pal(8, "Dark2"))(9)

thresh = as_labeller(c(`n_days_80F` ="Days \u226580\u00B0F",
              `n_days_90F`="Days \u226590\u00B0F",
              `n_days_100F`="Days \u2265100\u00B0F",
              `n_days_110F` ="Days \u2265100\u00B0F"))

## Plot graph
x <- df.n.county.reg.1 %>% 
  mutate(label = case_when(
    diff.avg.days > 0 ~ paste0("+ ", round(diff.avg.days,1)),
    diff.avg.days < 0 ~ paste0("- ", round(diff.avg.days,1)),
  )) %>%
  ggplot() + 
  geom_bar(aes(x = diff.avg.days, y = reorder(region_2, diff.avg.days), fill = region_2), stat = "identity", show.legend = FALSE ) + 
  geom_text(aes(x = diff.avg.days, y = reorder(region_2, diff.avg.days), label = label), hjust = -0.05, size = 2.05) + 
  theme_bw() +
  facet_wrap(~thresholds, ncol = 1, labeller = thresh) +
  scale_fill_manual(values = my_colours)+
  ylab("") +
  xlab("Average additional county co-exposure days") +
  expand_limits(x = 80) +
  theme(aspect.ratio = 0.7,
        strip.background = element_rect(fill = "white", color = "black"),
        strip.text = element_text(size = 6),
        axis.title.x = element_text(size = 6),
        text = element_text(size = 6)
        ) +
  canvas(width = 3.5, height = 5.5 ) #, units = "px")


```


## Fig 1B - Heat map of average county annual proportion of year with coexposure days above thresholds, by state from 2008-2023 
## 80F and 90F
```{r}
## Average annual county annual proportion of year with coexposure days above thresholds
df.HI.smoke.perc.annual <- df.HI.smoke %>%
    ### Count annual co-exposure days above threshold
  mutate(coexpos = if_else(smokePM_pred.wtd > 0 , "coexpos_days", "no coexpos"),
         coexpos = if_else(is.na(smokePM_pred.wtd), "no coexpos", coexpos)) %>%
  select(region_2, region_1, GEOID, STATEFIPS, STATEABB, CNTYFIPS, CNTYNAME, Year, month, month.abb, yearmonday, crop_class, total_county_crop_area, mean.HI.wtd, smokePM_pred.wtd, coexpos) %>%
  fgroup_by(region_2, region_1, GEOID, STATEFIPS, STATEABB, crop_class, coexpos, Year) %>%
  fsummarise(n_days_80F = fsum(mean.HI.wtd >=80   &  coexpos == "coexpos_days"),
             n_days_90F = fsum(mean.HI.wtd >=90   &  coexpos == "coexpos_days")
             )  %>%
  ungroup() %>%
    ### average annual coexposure day above threshold in county crop areas by state
  fgroup_by(region_2, region_1, STATEFIPS, STATEABB, crop_class, coexpos, Year) %>%
  fsummarise(n_days_80F = fmean(n_days_80F),
             n_days_90F = fmean(n_days_90F)) %>%
  pivot_longer(names_to = "thresholds",
               values_to = "n_Days",
               cols = 8:9) %>%
  mutate(`thresholds` = factor(`thresholds`, 
                                           levels = c("n_days_80F",
                                                      "n_days_90F"))) %>%
    ### proportion of year
  mutate(days_year = if_else(Year %in% c(2008,2012,2016,2020,2024), 366, 365),
         perc_of_year = n_Days / days_year ) %>%
  mutate(region_2 = factor(region_2, 
                           levels = c("West South Central",
                                      "East South Central",
                                      "South Atlantic",
                                      "West North Central",
                                      "East North Central",
                                      "Mountain",
                                      "Middle Atlantic",
                                      "Pacific",
                                      "New England"))) 


## df to set state order in heat plot
df.factor = df.HI.smoke.perc.annual %>%
  filter(thresholds == "n_days_80F",
         Year == 2023,
         crop_class == 1,
         coexpos == "coexpos_days") %>%
  group_by(thresholds) %>%
  arrange(region_2, -perc_of_year) %>%
  mutate(id = row_number(),
         STATEABB.2 = STATEABB,
         STATEABB = factor(STATEABB),
         STATEABB = fct_reorder(STATEABB, -id)
         )  %>%
  ungroup() %>%
  select(id, STATEABB, STATEABB.2 )

df.n.county.reg.1.2 <- full_join(df.factor, df.HI.smoke.perc.annual, by = c("STATEABB.2"= "STATEABB"))


# Plot heat map
x.1 <- df.n.county.reg.1.2 %>%
  filter(coexpos == "coexpos_days",
         crop_class == 1) %>%
  ggplot() + 
  geom_tile(aes(x = Year, y = STATEABB, fill = perc_of_year ), colour = "grey") +
  theme_bw() +
    coord_fixed(ratio = 1 ) +
  facet_grid2(~thresholds, switch = "y", labeller = thresh) + 
  scale_fill_viridis_c(labels = scales::percent) +
  labs(fill = "% of year") +
  ylab("") +
  xlab("") +
  xlim(2007,2024)  +
  theme(aspect.ratio = 4,
        strip.background = element_rect(fill = "white", color = "black"),
        strip.text = element_text(size = 6),
        axis.title.x = element_text(size = 6),
        text = element_text(size = 6),
        ) +
   guides(colour = guide_legend(position = "bottom", nrow=3,
                                theme(legend.key.size = unit(1, "mm")))) +
    canvas(width = 3.5, height = 5.5 ) 


```

Combine plots
```{r}
p <- (x  +  x.1 ) &
  plot_annotation(tag_levels = "A",
                  tag_suffix = ".") & 
  theme(plot.tag.position = c(0, 1),
        plot.tag = element_text(size = 20, hjust = 0, vjust = 1)) &
  canvas(width = 7, height = 5.5, dpi = 700) 
p
```

Save image
```{r}
filename = paste0(folder, "/03_outputs/Fig1_compos.png")
save_ggplot(p, filename)
```

