---
title: "10_Supplementary_Figures"
output: html_document
date: "2026-05-30"
editor_options: 
  chunk_output_type: console
---

PURPOSE: Create Supplementary Figures


```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(collapse)
library(sf)
library(tigris)
library(tmap)
library(openxlsx)
library(ggh4x)
library(patchwork)
library(scales)
library(RColorBrewer)

options(scipen = 99999)

knitr::opts_chunk$set(echo = TRUE)
```

# Read in files 
```{r}
folder = "ADD PATH HERE"

## Farmworkers 
file <- paste0(folder, "/01_data/01_farmworker_imputation_pred.rds")
df.farmworker <- readRDS(file) %>%
  mutate(variable = case_when(
    variable %in% c("Hired Labor", "Unpaid Labor") ~ "Hired+Unpaid Labor",
    variable == "Migrant Labor (incl hired)" ~ "Migrant Labor"
  )) %>%
  group_by(Year, STATEFIPS, STATEABB, STATENAME, CNTYFIPS, GEOID, region_2, region_1, variable) %>%
  summarise(across(c(n_farmworkers, n_farmworker_imput), ~sum(.))) %>%
  filter(Year %in% 2008:2023) 

## Days of exposure to HI above thresholds
file = paste0(folder, "/01a_final data/02_HI_2008-2023.rds")
df.HI <- readRDS(file ) %>%
  mutate(region_2 = factor(region_2, levels = c(  "East North Central" , "Middle Atlantic",   "New England" ,
                                                 "West South Central", "East South Central" , "South Atlantic",
                                                 "Pacific", "Mountain", "West North Central" ))) %>%
  mutate(month.abb = fct_reorder(month.abb, month))


## Days of co-exposure to HI above thresholds
file = paste0(folder, "/01a_final data/03_HI_smoke_2008-2023.rds")
df.HI.smoke <- readRDS(file ) %>%
  mutate(region_2 = factor(region_2, levels = c(  "East North Central" , "Middle Atlantic",   "New England" ,
                                                 "West South Central", "East South Central" , "South Atlantic",
                                                 "Pacific", "Mountain", "West North Central" ))) %>%
  mutate(month.abb = fct_reorder(month.abb, month))


## Counties sf
sf.counties <- counties(cb = TRUE, progress_bar = FALSE, year = 2021) %>%
  filter(!STUSPS %in% c("AK", 'HI', "PR", "AS", "MP", "GU", "VI")) %>%
  transmute(STATEFIPS = as.numeric( STATEFP), CNTYNAME = NAME, STATEABB = STUSPS, GEOID = as.numeric(GEOID))

## state sf
sf.states <- sf.counties %>%
  group_by(STATEABB) %>%
  summarise(totalFIPS = fsum(STATEFIPS)) %>%
  ungroup() %>%
  st_make_valid()
  
## region sf
sf.regions <- sf.counties %>%
  mutate(region_2 = case_when(
    STATEABB %in% c("CT", "ME", "MA", "NH", "VT", "RI") ~ "New England",
    STATEABB %in% c("NY", "PA", "NJ") ~ "Middle Atlantic",
    STATEABB %in% c("OH", "IN", "IL", "MI", "WI") ~ "East North Central",
    STATEABB %in% c("DE", "MD", "DC", "VA", "WV", "NC", "SC", "GA", "FL") ~ "South Atlantic",
    STATEABB %in% c("KY", "TN", "AL", "MS") ~ "East South Central",
    STATEABB %in% c("TX", "LA", "AR", "OK") ~ "West South Central",
    STATEABB %in% c("ND", "MN", "SD", "IA", "NE", "KS", "MO") ~ "West North Central",
    STATEABB %in% c("MT", "WY", "ID", "NV", "UT", "CO", "AZ", "NM" ) ~ "Mountain",
    STATEABB %in% c("WA", "OR", "CA") ~ "Pacific"
  ) ) %>%
  group_by(region_2) %>%
  summarise(totalFIPS = fsum(STATEFIPS)) %>%
  ungroup() %>%
  st_make_valid()
```


# Supplementary Figure 1 - Line graph of total FW-HI exposure days and FW-co-exposure days, 2008-2023, 80F
## Calculate FW-days / FW-coexposure days
```{r}
## FW-HI exposure days
df.HI.FW <- df.HI %>%
  fgroup_by(GEOID, region_2, region_1, STATEFIPS, STATEABB, CNTYFIPS, CNTYNAME,crop_class,Year ) %>%
  fsummarise(n_days = fsum(mean.HI.wtd >=80 , na.rm = TRUE)  ) %>%
  full_join(., df.farmworker) %>%
  mutate(thresholds = "n_days_80F") %>%
  mutate(FW_days = n_days * n_farmworker_imput) %>%
  filter(crop_class == 1,) %>%
  select(GEOID, region_2, Year, crop_class, thresholds, FW_days, variable)


# FW-Coexpos days
df.HI.smoke.FW <- df.HI.smoke %>%
  mutate(coexpos = if_else(smokePM_pred.wtd > 0 , "coexpos_days", "no coexpos"),
         coexpos = if_else(is.na(smokePM_pred.wtd), "no coexpos", coexpos)) %>%
    fgroup_by(GEOID, region_2, region_1, STATEFIPS, STATEABB, CNTYFIPS, CNTYNAME,crop_class,Year, coexpos ) %>%
  fsummarise(n_days = fsum(mean.HI.wtd >=80   &  coexpos == "coexpos_days")
             )  %>%
  full_join(., df.farmworker) %>%
  mutate(thresholds = "n_days_80F") %>%
  mutate(FW_coexpos_days = n_days * n_farmworker_imput) %>%
  filter(coexpos == "coexpos_days",
         crop_class == 1,) %>%
  select(GEOID, region_2, Year, crop_class, thresholds, FW_coexpos_days, variable)

# Join df for graph and calculate national FW-days / FW-coexposure days
df.hi.FW.coexpos <- full_join(df.HI.FW, df.HI.smoke.FW) %>%
  filter(variable == "Hired+Unpaid Labor") %>%
  ## sum for national estimate
  group_by(Year, crop_class, thresholds, variable) %>%
  summarise(across(c(FW_days, FW_coexpos_days), ~sum(., na.rm = TRUE))) %>%
  ungroup() %>%
  pivot_longer(names_to = "category",
               values_to = "FW_days",
               cols = 5:6) %>%
  mutate(category = case_when(
    category == "FW_days"  ~ "Farmworker-days",
    category == "FW_coexpos_days" ~ "Farmworker-days of coexposure"),
    category = factor(category, levels = c("Farmworker-days", "Farmworker-days of coexposure"))
  )

```


## Plot line graph
```{r}
x <- df.hi.FW.coexpos %>% 
  filter(thresholds %in% c("n_days_100F", "n_days_110F")) %>%
  ggplot() +
  geom_point(aes(x =Year, y= FW_days, colour = category), size = 0.5) +
  geom_line(aes(x =Year,  y= FW_days,  colour = category)) +
  theme_bw() +
    scale_y_continuous(
      name = "Farmworker-days (millions)",
      labels = label_number(scale = 1e-6 )  ) +
    scale_color_manual(values = c("#D95F02", "#1B9E77")) +
    facet_wrap(~thresholds, scales = "free", ncol = 1, labeller = thresh) +
  theme(aspect.ratio = 0.6) +
  theme(strip.background = element_rect(fill = "white", color = "black") ) +
    theme(legend.title = element_blank(),
          axis.title.x = element_blank(),
          text = element_text(size = 6, family = 'calibri')) +
  canvas(width = 6, height = 5.5 )

```




